name: 🌟 Feature request
description: Have a cool idea? Let's hear it!
labels: [enhancement, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        > 💁‍♂️ This is a collaborative effort. Please be polite & considerate, and follow this form.

  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: Before starting the issue...
      options:
        - label: I searched existing issues to avoid duplicates
          required: true

        - label: I understand tsx aims for TypeScript parity and is not for arbitrary Node.js enhancements
          required: true

        - label: This request cannot be made to Node.js directly, and is specific to tsx
          required: true

        - label: I understand this form is not for addressing a bug or seeking help
          required: true

        - label: I have read and understood the [Contribution guide](/CONTRIBUTING.md)
          required: true

  - type: markdown
    attributes:
      value: |
        ## 👀 Tell us about your idea

  - type: textarea
    attributes:
      label: Feature request
      description: A clear and concise description of the feature.
      placeholder: |
        I would love to be able to...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivations
      description: |
        Describe the problem you’re addressing with this feature request. If the motivation is feature parity, provide documentation links.
      placeholder: |
        How did you come across this idea?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Have you considered alternative solutions? Is there a workaround?
      placeholder: |
        Do you have alternative proposals?

        Are there workarounds?

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Anything else to share? (e.g. screenshots & links)

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > 🙋 Need help?
        >
        > Use [_Priority Support_](https://github.com/sponsors/privatenumber) for debugging help and implementation!

  - type: markdown
    attributes:
      value: |
        ## 🛠️ Contribute
        It would be amazing if you can contribute to the project! This project is open source, free to use, and maintained by volunteers. This could be a great opportunity to give back and improve the project for everyone, including yourself.

  - type: checkboxes
    attributes:
      label: Contributions
      options:
        - label: I plan to open a pull request for this issue
        - label: I plan to make a financial contribution to this project

  - type: markdown
    attributes:
      value: |
        ## 🚀 Need immediate help?
        Escalate this issue by supporting the project as a [_Priority Patron_](https://github.com/sponsors/privatenumber)! Your concern will receive prompt attention, ensuring faster and more efficient resolution.

        [→ Become a _Priority Patron_!](https://github.com/sponsors/privatenumber)
